/**
 * @file	leds_states.c
 * @brief  	Functions to control the states of the leds. It is the module used to control the leds.
 * 			If one tries to set a led outside of this module, it will probably not work as intended, as
 * 			this module updates the states of the leds.
 * 			Reads the events generated by the other modules in order to decide what to do with the leds
 * 
 * @written by  	Eliot Ferragni
 * @creation date	25.06.2018
 */

#ifndef LEDS_STATES_H
#define LEDS_TATES_H

#include "main.h"
#include "leds.h"

#define BLINK_TIME					100	//used when the target is running or when the robot is in low power state
#define COMMUNICATION_BLINK_TIME	10	//used when a communication is active

/**
* Starts the leds states thread
* Manages the red green and blue leds.
*/
void ledsStatesStart(void);

#endif  /* LEDS_STATES_H */