/**
 * @file	platform_commands.h
 * @brief  	Custom GDB commands added to the default ones
 * 
 * @written by  		Daniel Burnier
 * @creation date		11.08.2017
 * @modified by 		Eliot Ferragni
 * last modification	03.07.2018
 */

#if defined(PLATFORM_COMMANDS_DEFINE)
/********************************************/
/* Beginning of platform dedicated commands. */
/********************************************/

static bool cmd_en_esp32(target *t, int argc, const char **argv);
static bool cmd_gpio0_esp32(target *t, int argc, const char **argv);
static bool cmd_pwr_on_btn(target *t, int argc, const char **argv);
static bool cmd_vbus_hub(target *t, int argc, const char **argv);
static bool cmd_usb_charge(target *t, int argc, const char **argv);
static bool cmd_usb_500(target *t, int argc, const char **argv);
static bool cmd_reset_F407(target *t, int argc, const char **argv);
static bool cmd_esp32(target *t, int argc, const char **argv);
static bool cmd_select_mode(target *t, int argc, const char **argv);
static bool cmd_get_mode(target *t, int argc, const char **argv);

/***************************************/
/* End of platform dedicated commands. */
/***************************************/
#undef PLATFORM_COMMANDS_DEFINE
#endif

#if defined(PLATFORM_COMMANDS_LIST)
/****************************************************/
/* Beginning of List of platform dedicated commands. */
/* IMPORTANT : Each line MUST finish with "\"       */
/****************************************************/

	{"esp32", (cmd_handler)cmd_esp32, "Return the state of EN_ESP32 and GPIO0_ESP32 pins" }, \
	{"esp32_en", (cmd_handler)cmd_en_esp32, "(ON|OFF|) Set the EN_ESP32 pin or return the state of this one" }, \
	{"esp32_gpio0", (cmd_handler)cmd_gpio0_esp32, "(ON|OFF|) Set the GPIO0_ESP32 pin or return the state of this one" }, \
	{"pwr_on_btn", (cmd_handler)cmd_pwr_on_btn, "(ON|SHUTDOWN|) Power On or Shutdown the robot or return the state of Power On button" }, \
	{"vbus_hub", (cmd_handler)cmd_vbus_hub, "Return the state of VBus generated by the hub" }, \
	{"usb_charge", (cmd_handler)cmd_usb_charge, "(ON|OFF|) Set the USB_CHARGE pin or return the state of this one" }, \
	{"usb_500", (cmd_handler)cmd_usb_500, "(ON|OFF|) Set the USB_500 pin or return the state of this one" }, \
	{"reset_F407", (cmd_handler)cmd_reset_F407, "(ON|OFF|) Force the reset of F407" }, \
	{"select_mode", (cmd_handler)cmd_select_mode, "(0|1|2|3) Select the use of the second virtual com port over USB :\n\t\t0 = Programming/serial monitor of the ESP at 115200 bauds and GDB over USB,\n\t\t1 = Serial monitor of the main processor at 115200 bauds and GDB over USB and Bluetooth,\n\t\t2 = Programming/serial monitor of the ESP at 230400 baud and GDB over USB,\n\t\t3 = ASEBA CAN-USB translator and GDB over USB and Bluetooth\n\t    Add 4 then (4|5|6|7) to select temporary mode (0|1|2|3)\n\t    Will be lost when robot is power off and avoid to unnecessarily modify flash ."}, \
	{"get_mode", (cmd_handler)cmd_get_mode, "Return actual and saved mode in flash for the second virtual com port over USB"},\

/***********************************************/
/* End of List of platform dedicated commands. */
/***********************************************/
#undef PLATFORM_COMMANDS_LIST
#endif

#if defined(PLATFORM_COMMANDS_CODE)
/****************************************************/
/* Beginning of Code of platform dedicated commands. */
/****************************************************/

static bool cmd_version(target *t, int argc, char **argv)
{
	(void)t;
	(void)argc;
	(void)argv;
#if PC_HOSTED == 1
	gdb_outf("e-puck2 programmer, PC-Hosted for " PLATFORM_IDENT()
			 ", Version " FIRMWARE_VERSION "\n");
#else
	gdb_outf("e-puck2 programmer (Firmware " FIRMWARE_VERSION ") (Hardware Version %d)\n", platform_hwversion());
#endif
	gdb_out("<https://github.com/e-puck2/e-puck2-programmer>\n\n");

	return true;
}

static bool cmd_en_esp32(target *t, int argc, const char **argv)
{
	(void)t;
	if (argc == 1)
		gdb_outf("EN_ESP32 state: %s\n",
			 platform_get_en_esp32() ? "ON" : "OFF");
	else
		platform_set_en_esp32(strcmp(argv[1], "ON") == 0);
	return true;
}

static bool cmd_gpio0_esp32(target *t, int argc, const char **argv)
{
	(void)t;
	if (argc == 1)
		gdb_outf("GPIO0_ESP32 state: %s\n",
			 platform_get_gpio0_esp32() ? "ON" : "OFF");
	else
		platform_set_gpio0_esp32(strcmp(argv[1], "ON") == 0);
	return true;
}

static bool cmd_esp32(target *t, int argc, const char **argv)
{
	(void)t;
	(void) argv;
	if (argc == 1)
		gdb_outf("ESP32 state: EN %s - IO0 %s\n",
			 platform_get_en_esp32() ? "ON" : "OFF",
			 platform_get_gpio0_esp32() ? "ON" : "OFF");
	return true;
}

static bool cmd_pwr_on_btn(target *t, int argc, const char **argv)
{
	(void)t;
	if (argc == 1)
		gdb_outf("Power On button: %s\n",
			 isPowerButtonPressed() ? "Pressed" : "Released");
	else if (strcmp(argv[1], "SHUTDOWN") == 0)
		powerButtonTurnOnOff(POWER_OFF);
	else if (strcmp(argv[1], "ON") == 0)
		powerButtonTurnOnOff(POWER_ON);
	return true;
}

static bool cmd_vbus_hub(target *t, int argc, const char **argv)
{
	(void)t;
	(void)argv;
	if (argc == 1)
		gdb_outf("VBus: %s\n", platform_vbus_hub() ? "ON" : "OFF");
	return true;
}

static bool cmd_usb_charge(target *t, int argc, const char **argv)
{
	(void)t;
	if (argc == 1)
		gdb_outf("USB_CHARGE state: %s\n",
			 platform_get_usb_charge() ? "ON" : "OFF");
	else
		platform_set_usb_charge(strcmp(argv[1], "ON") == 0);
	return true;
}

static bool cmd_usb_500(target *t, int argc, const char **argv)
{
	(void)t;
	if (argc == 1)
		gdb_outf("USB_500 state: %s\n",
			 platform_get_usb_500() ? "ON" : "OFF");
	else
		platform_set_usb_500(strcmp(argv[1], "ON") == 0);
	return true;
}

static bool cmd_reset_F407(target *t, int argc, const char **argv)
{
	(void)t;
	if (argc == 1)
		gdb_outf("Reset F407 state: %s\n",
			gpio_get(SRST_PORT, SRST_PIN) ? "OFF" : "ON");
	else if (strcmp(argv[1], "ON") == 0)
		gpio_clear(SRST_PORT, SRST_PIN);
 	else
		gpio_set(SRST_PORT, SRST_PIN);
	return true;
}

const char error_message[] = "You must choose between mode 0, 1, 2 or 3 for saving it\n             or between mode 4, 5, 6 or 7 for temporary change\n             until next power cycle\n";
const char* mode_message[] = {"0 -> UART_ESP_PASSTHROUGH_115200",
							  "1 -> UART_407_PASSTHROUGH",
							  "2 -> UART_ESP_PASSTHROUGH_230400",
							  "3 -> ASEBA_CAN_TRANSLATOR"};

static bool cmd_select_mode(target *t, int argc, const char **argv){
	(void)t;
	bool continue_check = (argc > 1);
	if (continue_check) {
		comm_modes_t saved_mode = communicationGetSavedMode();
		comm_modes_t new_mode;
		continue_check = (strlen(argv[1])==1);
		if (continue_check) {
			bool is_temporary_mode = false;
			char mode_cmd = (argv[1])[0]-'0';
			switch (mode_cmd) {
				case TEMP_UART_ESP_PASSTHROUGH_115200:
					is_temporary_mode = true;
				case UART_ESP_PASSTHROUGH_115200:
					new_mode = UART_ESP_PASSTHROUGH_115200;
					break;

				case TEMP_UART_407_PASSTHROUGH:
					is_temporary_mode = true;
				case UART_407_PASSTHROUGH:
					new_mode = UART_407_PASSTHROUGH;
					break;

				case TEMP_UART_ESP_PASSTHROUGH_230400:
					is_temporary_mode = true;
				case UART_ESP_PASSTHROUGH_230400:
					new_mode = UART_ESP_PASSTHROUGH_230400;
					break;

				case TEMP_ASEBA_CAN_TRANSLATOR:
					is_temporary_mode = true;
				case ASEBA_CAN_TRANSLATOR:
					new_mode = ASEBA_CAN_TRANSLATOR;
					break;
				default:
					continue_check = false;
					break;
			}
			if (continue_check) {
				if (is_temporary_mode) {
					communicationsSwitchModeTo(new_mode, false);
					if (new_mode == saved_mode) {
						gdb_outf("Switched to mode %s, the same as saved one\n", mode_message[new_mode]);
					} else {
						gdb_outf("Switched temporarily to mode %s, the saved one being %s\n", mode_message[new_mode], mode_message[saved_mode]);
					}
				} else {
					communicationsSwitchModeTo(new_mode, true);
					gdb_outf("Switched to mode %s\n", mode_message[new_mode]);
				}
			}
		}
	}
	if (! continue_check) {
		gdb_outf("%s",error_message);
	}
 	return true;
}

static bool cmd_get_mode(target *t, int argc, const char **argv)
{
	(void)t;
	(void)argc;
	(void)argv;
	comm_modes_t saved_mode = communicationGetSavedMode();
	comm_modes_t actual_mode = communicationGetActiveMode();

	if (actual_mode == saved_mode) {
		gdb_outf("Active mode %s, the same as saved one\n", mode_message[actual_mode]);
	} else {
		gdb_outf("Temporary mode %s, the saved one being %s\n", mode_message[actual_mode], mode_message[saved_mode]);
	}
	return true;
}


/***********************************************/
/* End of Code of platform dedicated commands. */
/***********************************************/
#undef PLATFORM_COMMANDS_CODE
#endif
